// ===========================================================================
// VA 0x004BF3E0 - ModelLoadPMD  (original: sub_4BF3E0, 0x2C95 bytes)
// ===========================================================================
// The PMD binary parser, __thiscall on the freshly initialised 0x4CCF4
// model block.  Signature (verified against the 0x46050F push sequence):
//
//   model->LoadPMD(a2 hwnd, a3 widePath, a4 sub1d574, a5 app+0xA06CE,
//                  a6 = 1, a7 englishUI, a8 sub048ptr, a9 appPathBuf)
//
// a7 (EnglishUI, *(app+0xA0B4C)) is stored to m+12740 and gates all
// English-vs-Japanese message paths; a8 (*(app+0x9EDB0), the 0x48-byte
// subsystem object) is stored to m+60 and doubles as the physics scene
// wrapper (gizmo buffers +4..44, constraint-id counter +56,
// btDiscreteDynamicsWorld* +64).  The loader's physics section passes
// m+60 to 0x4064F0/0x406010.
//
// The file is opened with the wide CRT entry (0x50747B - actually
// _wsopen_s; the FLIRT name __sopen_s is a mislabel, see
// docs/ARCHITECTURE.md).  Material/texture names are narrow Shift-JIS
// and converted via 0x407DA0; file opens probe through 0x4089F0 and the
// shared texture cache 0x407490.
//
// Physics (rigid bodies + joints) is parsed and its transform chains
// computed with the same D3DX calls as the original; body/constraint
// creation goes through the ported 0x4064F0/0x406010 (null-world
// guarded until the 0x4032B0 scene constructor lands).
// =========================================================================//
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <Windows.h>
#include <d3d9.h>

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cwchar>
#include <cmath>

#include <fcntl.h>
#include <io.h>
#include <share.h>
#include <sys/stat.h>

#include "mikudancestudio/d3dx_dyn.hpp"
#include "mikudancestudio/d3d_wrapper.hpp"
#include "mikudancestudio/model.hpp"
#include "mikudancestudio/path_workspace.hpp"
#include "mikudancestudio/ported_funcs.hpp"

namespace mikudancestudio {
namespace {

// GENERATED by scripts/gen_model_labels.py - do not edit.
#include "model_labels.inc"

using mdl::At;

IDirect3DDevice9* DevOf(D3DRenderer* sub) {
    return sub->device;                       // wrapper + 120032
}

bool FailBox(HWND hwnd, bool en, bool enData, const char* enMsg,
             const char* jpMsg, const char* enTitle, const char* jpTitle) {
    char text[256];
    if (enData) {
        sprintf_s(text, 0x100, "%s", enMsg);
        MessageBoxA(hwnd, text, enTitle, 0);
    } else {
        sprintf_s(text, 0x100, "%s", jpMsg);
        MessageBoxA(hwnd, text, jpTitle, 0);
    }
    return false;
}

// Porting-era trace under MIKUDANCESTUDIO_PMM_TRACE_DIR (CMake option
// MIKUDANCESTUDIO_DIAG, default OFF); the OFF stub keeps the call site
// valid and inlines away to nothing.
#ifdef MIKUDANCESTUDIO_DIAG
void LogPmdRigid(const wchar_t* path, std::uint32_t rigidIndex,
                 std::int32_t boneIndex, std::uint32_t boneCount,
                 const void* bones) {
    const char* dir = std::getenv("MIKUDANCESTUDIO_PMM_TRACE_DIR");
    if (dir == nullptr || dir[0] == '\0')
        return;
    char logPath[MAX_PATH];
    sprintf_s(logPath, "%s\\pmm_model_load.log", dir);
    FILE* stream = nullptr;
    if (fopen_s(&stream, logPath, "ab") != 0 || stream == nullptr)
        return;
    fprintf(stream, "pmd-rigid path=%ls rigid=%lu bone=%ld bone_count=%lu "
                    "bones=%p\r\n",
            path != nullptr ? path : L"", static_cast<unsigned long>(rigidIndex),
            static_cast<long>(boneIndex), static_cast<unsigned long>(boneCount),
            bones);
    fclose(stream);
}
#else
inline void LogPmdRigid(const wchar_t*, std::uint32_t, std::int32_t,
                        std::uint32_t, const void*) {}
#endif


}  // namespace

bool ModelLoadPMD(unsigned char* m, HWND hwnd, const wchar_t* path,
                  D3DRenderer* sub, int unusedA06CE, std::uint8_t boxGate,
                  std::uint8_t englishUi, PhysicsScene* sub048,
                  PathResolutionWorkspace& paths) {          // 0x4BF3E0
    // Arg map (original 0x46050F call site, pushes -0x20..-0x4; the
    // trailing (aN) tags are the original decompiler parameter names):
    //   a2 hwnd, a3 path, a4 sub1d574 (device), unusedA06CE (a5) app+0xA06CE
    //   (unused), boxGate (a6) constant 1 (message-box gate), englishUi
    //   (a7) EnglishUI *(app+0xA0B4C) (stored to m+12740), sub048 (a8) the
    //   0x048 pointer *(app+0x9EDB0), typed as PhysicsScene* (stored to
    //   m+60 - the physics scene wrapper: gizmos +4..44, constraint-id
    //   counter +56, btDiscreteDynamicsWorld* +64), a9 appPathBuf.
    const bool enData = englishUi != 0;
    mdl::ModelRecord& model = *mdl::Mdl(m);
    char text[256];
    wchar_t wide1[256], wide2[384], wide3[384];

    model.hwnd = hwnd;
    model.scenePtr = sub048;               // 0x4BF42B
    model.physicsFlags = englishUi;           // 0x4BF431: English-data byte

    ResolveUserFilePath(paths, path);                         // 0x4089F0
    wcscpy_s(model.path, 0x100, paths.resolvedPath);

    int fh = -1;
    errno_t err = _wsopen_s(&fh,
        model.path,
        _O_BINARY, _SH_DENYNO, _S_IREAD);
    if (err != 0) {
        if (boxGate) {
            if (enData)
                sprintf_s(text, 0x100,
                          "Cannot open file:%d\n"
                          "\n"
                          "If Japanese font is included in the filename"
                          "(*.pmd),please rewrite it in English font.",
                          err),
                MessageBoxA(hwnd, text, "open file", 0);
            else
                sprintf_s(text, 0x100, "%s:%d", kMsgOpenFailJp, err),
                MessageBoxA(hwnd, text, kTitleOpenFailJp, 0);
        }
        return false;
    }

    // directory of the model file -> current directory
    wcscpy_s(model.modelDirectory, 0x100, model.path);
    {
        wchar_t* p = model.modelDirectory;
        while (*p) ++p;
        if (*p != L'\\')
            do {
                --p;
            } while (p != model.modelDirectory &&
                     *p != L'\\');
        p[1] = L'\0';
        SetCurrentDirectoryW(model.modelDirectory);
    }

    // ---- header -----------------------------------------------------------
    _read(fh, text, 3);
    if (text[0] != 'P' || text[1] != 'm' || text[2] != 'd') {
        if (text[0] == 'P' && text[1] == 'M' && text[2] == 'X')
            return LoadPMX(m, sub, boxGate, englishUi, paths,
                           fh);                              // 0x4B77E0
    _close(fh);
        if (enData) {
            sprintf_s(text, 0x100, "This file is not for Ploygon Movie Maker !!");
            MessageBoxA(hwnd, text, "open file", 0);
        } else {
            sprintf_s(text, 0x100, "%s", kMsgNotPmdJp);
            MessageBoxA(hwnd, text, kTitleOpenFailJp, 0);
        }
        return false;
    }
    _read(fh, text, 4);                                   // version
    _read(fh, model.name, mdl::kPmdModelNameBytes);
    _read(fh, model.comment, sizeof(model.comment));
    if (!enData && boxGate &&
        MessageBoxA(hwnd, model.comment,
                    kTitleModelInfoJp, 0x40001u) != 1) {
        _close(fh);
        return false;
    }

    IDirect3DDevice9* dev = DevOf(sub);
    auto* d3dx = &d3dx::Get();
    const bool haveD3dx = d3dx->Load();

    // ---- vertices ---------------------------------------------------------
    _read(fh, &model.vertexCount, sizeof(model.vertexCount));
    const std::uint32_t vertCount = model.vertexCount;
    if (vertCount != 0) {
        if (dev == nullptr) {
            return false;
        }
        if (FAILED(dev->CreateVertexBuffer(32 * vertCount, 8, 274 /*FVF*/,
                                          D3DPOOL_MANAGED,
                                          &mdl::ResourceAs<IDirect3DVertexBuffer9>(
                                              mdl::Mdl(m)->vertexBuffer),
                                          nullptr))) {
            FailBox(hwnd, true, enData,
                    "The performance of the graphics card doesn't suffice.",
                    kMsgNoPerfJp, "open file", kTitleOpenFailJp);
            _close(fh);
            return false;
        }
        if (FAILED(dev->CreateVertexBuffer(16 * vertCount, 8, 66 /*FVF*/,
                                          D3DPOOL_MANAGED,
                                          &mdl::ResourceAs<IDirect3DVertexBuffer9>(
                                              mdl::Mdl(m)->vertexBuffer2),
                                          nullptr))) {
            FailBox(hwnd, true, enData,
                    "The performance of the graphics card doesn't suffice.",
                    kMsgNoPerfJp, "open file", kTitleLoad2Jp);
            _close(fh);
            return false;
        }
        mdl::PmdVertex* recs = static_cast<mdl::PmdVertex*>(
            operator new(sizeof(mdl::PmdVertex) * vertCount));
        model.rawVertices = recs;
        std::memset(recs, 0, sizeof(mdl::PmdVertex) * vertCount);
        for (std::uint32_t i = 0; i < vertCount; ++i)
            _read(fh, &recs[i], 0x26);

        float* p1 = nullptr;
        if (SUCCEEDED(mdl::ResourceAs<IDirect3DVertexBuffer9>(
                          mdl::Mdl(m)->vertexBuffer)->Lock(
                0, 32 * vertCount,
                reinterpret_cast<void**>(&p1), 0))) {
            for (std::uint32_t i = 0; i < vertCount; ++i) {
                float* dst = reinterpret_cast<float*>(
                    reinterpret_cast<unsigned char*>(p1) + 32 * i);
                std::memcpy(dst, &recs[i], 32);
            }
            mdl::ResourceAs<IDirect3DVertexBuffer9>(
                mdl::Mdl(m)->vertexBuffer)->Unlock();
        }
        float* p2 = nullptr;
        if (SUCCEEDED(mdl::ResourceAs<IDirect3DVertexBuffer9>(
                          mdl::Mdl(m)->vertexBuffer2)->Lock(
                0, 16 * vertCount,
                reinterpret_cast<void**>(&p2), 0))) {
            for (std::uint32_t i = 0; i < vertCount; ++i) {
                unsigned char* dst =
                    reinterpret_cast<unsigned char*>(p2) + 16 * i;
                std::memcpy(dst, recs[i].position, 12);
                *reinterpret_cast<std::uint32_t*>(dst + 12) = 0xFF000000u;
            }
            mdl::ResourceAs<IDirect3DVertexBuffer9>(
                mdl::Mdl(m)->vertexBuffer2)->Unlock();
        }
    }

    // ---- indices ----------------------------------------------------------
    _read(fh, &model.indexCount, sizeof(model.indexCount));
    const std::uint32_t idxCount = model.indexCount;
    if (idxCount != 0) {
        if (dev == nullptr)
            return false;
        if (FAILED(dev->CreateIndexBuffer(2 * idxCount, 0,
                                          static_cast<D3DFORMAT>(101),
                                          D3DPOOL_MANAGED,
                                          &mdl::ResourceAs<IDirect3DIndexBuffer9>(
                                              mdl::Mdl(m)->indexBuffer),
                                          nullptr))) {
            FailBox(hwnd, true, enData,
                    "The performance of the graphics card doesn't suffice.",
                    kMsgNoPerfJp, "CreateIndexBuffer", "CreateIndexBuffer");
            _close(fh);
            return false;
        }
        std::uint16_t*& idx = mdl::Indices(m);
        idx = static_cast<std::uint16_t*>(operator new(4 * idxCount));
        std::memset(idx, 0, 4 * idxCount);
        void* ib = nullptr;
        if (FAILED(mdl::ResourceAs<IDirect3DIndexBuffer9>(
                       mdl::Mdl(m)->indexBuffer)->Lock(0, 0, &ib, 0))) {
            FailBox(hwnd, true, enData,
                    "The performance of the graphics card doesn't suffice.",
                    kMsgNoPerfJp, "pIndBuf->Lock", "pIndBuf->Lock");
            _close(fh);
            return false;
        }
        for (std::uint32_t j = 0; j < idxCount; ++j) {
            _read(fh, idx + 2 * j, 2);
            static_cast<std::uint16_t*>(ib)[j] = idx[2 * j];
        }
        mdl::ResourceAs<IDirect3DIndexBuffer9>(
            mdl::Mdl(m)->indexBuffer)->Unlock();
    }

    // ---- materials --------------------------------------------------------
    _read(fh, &mdl::Mdl(m)->materialCount,
          sizeof mdl::Mdl(m)->materialCount);
    const std::uint32_t matCount = mdl::Mdl(m)->materialCount;
    if (matCount != 0) {
        mdl::ModelMaterialRecord*& materials = mdl::Materials(m);
        materials = static_cast<mdl::ModelMaterialRecord*>(
            operator new(sizeof(*materials) * matCount));
        std::memset(materials, 0, sizeof(*materials) * matCount);
        for (std::uint32_t i = 0; i < matCount; ++i) {
            mdl::ModelMaterialRecord& mat = materials[i];
            _read(fh, mat.diffuse, sizeof(mat.diffuse));
            std::memcpy(mat.diffuseMirror, mat.diffuse,
                        sizeof(mat.diffuseMirror));
            _read(fh, &mat.specularPower, sizeof(mat.specularPower));
            _read(fh, mat.specular, sizeof(mat.specular));
            _read(fh, mat.ambient, sizeof(mat.ambient));
            _read(fh, &mat.toonReference, sizeof(mat.toonReference));
            std::uint8_t sphereFlag = 0;
            _read(fh, &sphereFlag, 1);
            mat.doubleSided = sphereFlag ? 1 : 0;
            _read(fh, &mat.faceVertexCount, sizeof(mat.faceVertexCount));
            char texName[24] = {};
            _read(fh, texName, 0x14);
            if (texName[0] != '\0') {
                const wchar_t* dirW = model.modelDirectory;
                char* star = strstr(texName, "*");
                if (star != nullptr) {
                    *star = '\0';
                    unsigned char* subBytes =
                        reinterpret_cast<unsigned char*>(sub);
                    ConvertMaterialName(subBytes, texName, wide1, 0x100,
                                        dirW);
                    swprintf_s(wide2, 0x180, L"%s%s", dirW, wide1);
                    LoadTextureShared(subBytes, wide2);      // 0x407490
                    ConvertMaterialName(subBytes, star + 1, wide1, 0x100,
                                        dirW);
                    swprintf_s(wide3, 0x180, L"%s%s", dirW, wide1);
                    if (LoadTextureShared(subBytes, wide3))
                        wcscpy_s(mat.spherePath, 0x118, wide3);
                    wcscpy_s(mat.texturePath, 0x118, wide2);
                } else {
                    unsigned char* subBytes =
                        reinterpret_cast<unsigned char*>(sub);
                    ConvertMaterialName(subBytes, texName, wide1, 0x100,
                                        dirW);
                    swprintf_s(wide2, 0x180, L"%s%s", dirW, wide1);
                    LoadTextureShared(subBytes, wide2);
                    wcscpy_s(mat.texturePath, 0x118, wide2);
                }
            }
        }
    }

    // ---- bones ------------------------------------------------------------
    _read(fh, &model.boneCount, 2);
    const std::uint32_t boneCount = model.boneCount;
    mikudancestudio::mdl::BoneRecord* bones = static_cast<mikudancestudio::mdl::BoneRecord*>(
        operator new(sizeof(mikudancestudio::mdl::BoneRecord) * (boneCount ? boneCount : 1)));
    mikudancestudio::mdl::Bones(m) = bones;
    std::memset(bones, 0, sizeof(mikudancestudio::mdl::BoneRecord) * (boneCount ? boneCount : 1));
    {
        void* t1 = operator new(4 * (boneCount ? boneCount : 1));
        std::memset(t1, 0, 4 * (boneCount ? boneCount : 1));
        mdl::Mdl(m)->boneKeyCursors = static_cast<std::uint32_t*>(t1);
        void* t2 = operator new(boneCount ? boneCount : 1);
        std::memset(t2, 0, boneCount ? boneCount : 1);
        mdl::Mdl(m)->boneTrackActive = static_cast<unsigned char*>(t2);
        void* t3 = operator new(boneCount ? boneCount : 1);
        std::memset(t3, 0, boneCount ? boneCount : 1);
        mdl::Mdl(m)->boneSelection = static_cast<unsigned char*>(t3);
        static_cast<unsigned char*>(t3)[0] = 1;
        void* t4 = operator new(boneCount ? boneCount : 1);
        std::memset(t4, 0, boneCount ? boneCount : 1);
        mdl::Mdl(m)->bonePhysicsState = static_cast<unsigned char*>(t4);
    }
    std::uint8_t centerSeen = 0;
    for (std::uint32_t i = 0; i < boneCount; ++i) {
        mikudancestudio::mdl::BoneRecord* bone = &bones[i];
        _read(fh, bone->name, sizeof(bone->name));
        if (!std::memcmp(bone->name, kNameCenter2Jp, 9)) {
            model.centerBone = static_cast<std::int32_t>(i);
            centerSeen = 1;
        }
        if (!std::memcmp(bone->name, kNameCenterJp, 9) && !centerSeen)
            model.centerBone = static_cast<std::int32_t>(i);
        std::int16_t parent = 0;
        _read(fh, &parent, 2);
        bone->parent = parent;
        std::int16_t tail = 0;
        _read(fh, &tail, 2);
        bone->tailBone = tail;
        _read(fh, &bone->type, 1);       // type
        std::int16_t tailIdx = 0;
        _read(fh, &tailIdx, 2);
        bone->tailIdx = tailIdx;
        _read(fh, bone->position, sizeof(bone->position));
        bone->rotQuat[3] = 1.0f;    // scale x/y
        bone->rotQuat2[3] = 1.0f;
        for (int f = 0; f < 16; ++f)  // +180 identity (x64 0x7FF7CB4D34B0)
            bone->matWorld[f] = (f % 5 == 0) ? 1.0f : 0.0f;
        bone->slotIndex = -1;
        bone->rigidIdx = -296;
        bone->flags |= mikudancestudio::mdl::kBoneFlagVisible;
    }

    // ---- IK chains --------------------------------------------------------
    _read(fh, &model.ikChainCount, 2);
    const std::uint32_t ikCount = model.ikChainCount;
    if (ikCount > 0) {
        mdl::Mdl(m)->ikChains = static_cast<mdl::IkChain*>(
            operator new(sizeof(mdl::IkChain) * ikCount));
        std::memset(mdl::Mdl(m)->ikChains, 0,
                    sizeof(mdl::IkChain) * ikCount);
        for (std::uint32_t i = 0; i < ikCount; ++i) {
            mdl::IkChain& ik = mdl::IkChains(m)[i];
            _read(fh, &ik.boneIndex, 2);
            _read(fh, &ik.targetBone, 2);
            _read(fh, &ik.linkCount, 1);
            _read(fh, &ik.iterations, 2);
            _read(fh, &ik.maxAngle, 4);
            ik.enabled = 1;
            const std::uint8_t len = ik.linkCount;
            ik.links = static_cast<std::uint16_t*>(
                operator new(sizeof(std::uint16_t) * len));
            for (std::uint8_t k = 0; k < len; ++k)
                _read(fh, &ik.links[k], sizeof(ik.links[k]));
        }
    }

    // physics-driven bone sweep (0x4C0258, C precedence kept verbatim:
    // (parent flagged) || ((RotateGrant || (inherit-flags && physMode==2))
    // && tail is Ik/UnderIk) - RotateGrant is NOT gated by physMode)
    for (std::uint32_t i = 0; i < boneCount; ++i) {
        mikudancestudio::mdl::BoneRecord* bone = &bones[i];
        bone->hasFlag = 0;
        const std::int32_t parent = bone->parent;
        const std::int32_t tail = bone->tailIdx;
        const mikudancestudio::mdl::BoneType tailType = bones[tail].type;
        const bool arm1 =
            parent >= 0 &&
            mikudancestudio::mdl::Bones(m)[parent].hasFlag != 0;
        const bool arm2 =
            (bone->type == mikudancestudio::mdl::BoneType::RotateGrant ||
             ((bone->flags & mikudancestudio::mdl::kBoneFlagInheritMask) != 0 &&
              model.physicsMode == 2)) &&
            (tailType == mikudancestudio::mdl::BoneType::Ik ||
             tailType == mikudancestudio::mdl::BoneType::UnderIk);
        bone->hasFlag = (arm1 || arm2) ? 1 : 0;
    }
    InitBoneSortOrder(m);                                    // 0x490070 stub

    // ---- morphs -----------------------------------------------------------
    // (original 0x4C0330..0x4C0613: per-morph offset table of 16-byte
    //  entries is allocated at +92 and read from the file - four separate
    //  4-byte reads.  No group byte and no bone-style init; the earlier
    //  port invented both, writing past the 136-byte records and
    //  desynchronising the stream - heap corruption with real models,
    //  docs/ARCHITECTURE.md §8.)
    _read(fh, &model.morphCount, 2);
    const std::uint32_t morphCount = model.morphCount;
    if (morphCount > 0) {
        mdl::MorphRecord* morphs = static_cast<mdl::MorphRecord*>(
            operator new(sizeof(mdl::MorphRecord) * morphCount));
        mdl::Morphs(m) = morphs;
        std::memset(morphs, 0, sizeof(mdl::MorphRecord) * morphCount);
        void* w1 = operator new(4 * morphCount);
        std::memset(w1, 0, 4 * morphCount);
        mdl::Mdl(m)->morphKeyCursors = static_cast<std::uint32_t*>(w1);
        void* w2 = operator new(morphCount);
        std::memset(w2, 0, morphCount);
        mdl::Mdl(m)->morphTrackActive = static_cast<unsigned char*>(w2);
        for (std::uint32_t i = 0; i < morphCount; ++i) {
            mdl::MorphRecord& morph = morphs[i];
            _read(fh, morph.name, sizeof(morph.name));
            _read(fh, &morph.offsetCount, sizeof(morph.offsetCount));
            _read(fh, &morph.panel, sizeof(morph.panel));
            const std::uint32_t n = morph.offsetCount;
            morph.vertexEntries = static_cast<mdl::PmdVertexMorphEntry*>(
                operator new(sizeof(mdl::PmdVertexMorphEntry) * n));
            std::memset(morph.vertexEntries, 0,
                        sizeof(mdl::PmdVertexMorphEntry) * n);
            for (std::uint32_t k = 0; k < n; ++k) {
                _read(fh, &morph.vertexEntries[k].vertexIndex, 4);
                _read(fh, morph.vertexEntries[k].offset, 12);
            }
        }
    }
    // first-morph table shared copy (this[2171] count / this[2181] table),
    // then remap every later morph's entry index through morph 0's table
    // (0x4C05EB: entry[0] = firstTable[16 * entry[0]]).
    {
        mdl::MorphRecord* morphs = mdl::Morphs(m);
        if (morphs != nullptr) {
            const std::uint32_t n = morphs[0].offsetCount;
            mdl::BaseVertexMorphCount(m) = n;
            mdl::BaseVertexMorphTable(m) = static_cast<mdl::PmdVertexMorphEntry*>(
                operator new(sizeof(mdl::PmdVertexMorphEntry) * n));
            std::memset(mdl::BaseVertexMorphTable(m), 0,
                        sizeof(mdl::PmdVertexMorphEntry) * n);
            std::memcpy(mdl::BaseVertexMorphTable(m), morphs[0].vertexEntries,
                        sizeof(mdl::PmdVertexMorphEntry) * n);
            for (std::uint32_t i = 1; i < morphCount; ++i) {
                mdl::MorphRecord& morph = morphs[i];
                for (std::uint32_t k = 0;
                     k < static_cast<std::uint32_t>(morph.offsetCount); ++k) {
                    mdl::PmdVertexMorphEntry& entry = morph.vertexEntries[k];
                    entry.vertexIndex = mdl::BaseVertexMorphTable(m)[entry.vertexIndex]
                        .vertexIndex;
                }
            }
        }
    }

    // ---- display frames / face groups -------------------------------------
    _read(fh, &model.facialFrameCount, sizeof(model.facialFrameCount));
    if (model.facialFrameCount != 0) {
        model.displayFrames = static_cast<mdl::FrameGroup*>(
            operator new(sizeof(*model.displayFrames) * model.facialFrameCount));
        std::memset(model.displayFrames, 0,
                    sizeof(*model.displayFrames) * model.facialFrameCount);
        for (std::uint8_t i = 0; i < model.facialFrameCount; ++i) {
            mdl::FrameGroup& frame = model.displayFrames[i];
            _read(fh, &frame.targetIndex, sizeof(frame.targetIndex));
            frame.groupIndex = 1;
            strcpy_s(frame.name, sizeof(frame.name),
                     mdl::Morphs(m)[frame.targetIndex].name);
        }
    }
    _read(fh, &model.groupCount, sizeof(model.groupCount));
    model.groupCount += 2;
    if (model.facialFrameCount != 0)
        ++model.groupCount;
    const std::uint8_t grpCount = model.groupCount;
    mdl::DisplayGroup*& groups = mdl::DisplayGroups(m);
    groups = static_cast<mdl::DisplayGroup*>(
        operator new(sizeof(*groups) * (grpCount ? grpCount : 1)));
    std::memset(groups, 0, sizeof(*groups) * (grpCount ? grpCount : 1));
    strcpy_s(groups[0].name, sizeof(groups[0].name), bones[0].name);
    strcpy_s(groups[1].name, sizeof(groups[1].name), kLblDispIkOpJp);
    strcpy_s(groups[0].nameEn, sizeof(groups[0].nameEn), bones[0].nameEn);
    strcpy_s(groups[1].nameEn, sizeof(groups[1].nameEn), "Disp/IK/OP");
    if (model.facialFrameCount != 0) {
        strcpy_s(groups[2].name, sizeof(groups[2].name), kLblFacialJp);
        strcpy_s(groups[2].nameEn, sizeof(groups[2].nameEn), "Facial");
        for (std::uint8_t i = 3; i < grpCount; ++i)
            _read(fh, groups[i].name, sizeof(groups[i].name));
    } else {
        for (std::uint8_t i = 2; i < grpCount; ++i)
            _read(fh, groups[i].name, sizeof(groups[i].name));
    }

    // ---- rigid-body group list --------------------------------------------
    _read(fh, &model.rigidBodyCount, sizeof(model.rigidBodyCount));
    const std::uint32_t rbGroupCount = model.rigidBodyCount;
    mdl::FrameGroup*& rbGroups = mdl::RigidGroups(m);
    rbGroups = static_cast<mdl::FrameGroup*>(
        operator new(sizeof(*rbGroups) * (rbGroupCount ? rbGroupCount : 1)));
    std::memset(rbGroups, 0,
                sizeof(*rbGroups) * (rbGroupCount ? rbGroupCount : 1));
    for (std::uint32_t i = 0; i < rbGroupCount; ++i) {
        mdl::FrameGroup& rb = rbGroups[i];
        _read(fh, &rb.targetIndex, sizeof(rb.targetIndex));
        _read(fh, &rb.groupIndex, 1);
        ++rb.groupIndex;
        if (model.facialFrameCount != 0)
            ++rb.groupIndex;
        strcpy_s(rb.name, sizeof(rb.name), bones[rb.targetIndex].name);
    }

    // ---- English names section --------------------------------------------
    std::int8_t hasEn = 0;
    const int enRead = _read(fh, &hasEn, 1);
    if (hasEn == 0 || enRead == 0) {
        if ((boxGate & model.physicsFlags) != 0)
            MessageBoxA(hwnd,
                        "For this model, there is no English data.\n"
                        "\n"
                        "The model name is expressed in Japanese.\n"
                        "If Japanese Font is not installed in your PC, "
                        "the name display will become abnormal.",
                        "warning!", 0);
        strcpy_s(model.nameEn, 0x32, model.name);
        strcpy_s(model.commentEn, sizeof(model.commentEn), model.comment);
        for (std::uint32_t i = 0; i < boneCount; ++i)
            strcpy_s(reinterpret_cast<char*>(&bones[i].nameEn[0]), 0x14,
                     reinterpret_cast<const char*>(&bones[i]));
        mdl::MorphRecord* morphs = mdl::Morphs(m);
        for (std::uint32_t i = 0; i < morphCount; ++i)
            strcpy_s(morphs[i].nameEn, sizeof(morphs[i].nameEn),
                     morphs[i].name);
        if (model.facialFrameCount != 0)
            for (std::uint8_t i = 3; i < grpCount; ++i)
                strcpy_s(groups[i].nameEn, sizeof(groups[i].nameEn),
                         groups[i].name);
        else
            for (std::uint8_t i = 2; i < grpCount; ++i)
                strcpy_s(groups[i].nameEn, sizeof(groups[i].nameEn),
                         groups[i].name);
    } else {
        _read(fh, model.nameEn, mdl::kPmdModelNameBytes);
        model.nameEn[19] = 0;
        _read(fh, model.commentEn, sizeof(model.commentEn));
        model.commentEn[255] = 0;
        if (model.physicsFlags != 0 && boxGate &&
            MessageBoxA(hwnd, model.commentEn,
                        "model infomation", 0x40001u) != 1) {
            _close(fh);
            return false;
        }
        for (std::uint32_t i = 0; i < boneCount; ++i) {
            _read(fh, &bones[i].nameEn[0], 0x14);
            bones[i].nameEn[19] = 0;
        }
        mdl::MorphRecord* morphs = mdl::Morphs(m);
        for (std::uint32_t i = 1; i < morphCount; ++i) {
            _read(fh, morphs[i].nameEn, sizeof(morphs[i].nameEn));
            morphs[i].nameEn[sizeof(morphs[i].nameEn) - 1] = 0;
        }
        if (model.facialFrameCount != 0)
            for (std::uint8_t i = 3; i < grpCount; ++i) {
                _read(fh, groups[i].nameEn, sizeof(groups[i].nameEn));
                groups[i].nameEn[sizeof(groups[i].nameEn) - 1] = 0;
            }
        else
            for (std::uint8_t i = 2; i < grpCount; ++i) {
                _read(fh, groups[i].nameEn, sizeof(groups[i].nameEn));
                groups[i].nameEn[sizeof(groups[i].nameEn) - 1] = 0;
            }
    }
    for (std::uint8_t i = 0; i < model.facialFrameCount; ++i) {
        mdl::FrameGroup& frame = model.displayFrames[i];
        strcpy_s(frame.nameEn, sizeof(frame.nameEn),
                 mdl::Morphs(m)[frame.targetIndex].nameEn);
    }
    for (std::uint32_t i = 0; i < rbGroupCount; ++i)
        strcpy_s(rbGroups[i].nameEn, sizeof(rbGroups[i].nameEn),
                 bones[rbGroups[i].targetIndex].nameEn);

    // ---- toon references --------------------------------------------------
    if (enRead != 0) {
        auto* toon = model.pmdToonFileNames;
        for (int i = 0; i < 10; ++i) {
            _read(fh, toon[i], sizeof(toon[i]));
            std::uint8_t matched = 0;
            for (int k = 0; k < 10; ++k) {
                sprintf_s(text, 0x100, "toon%02d.bmp", k + 1);
                if (!strcmp(toon[i], text))
                    matched = 1;
            }
            if (!matched) {
                ConvertAnsiToWide(reinterpret_cast<unsigned char*>(sub),
                                  toon[i], wide1, 0x100);
                swprintf_s(wide2, 0x180, L"%s%s",
                           model.modelDirectory,
                           wide1);
                if (!LoadTextureShared(
                        reinterpret_cast<unsigned char*>(sub), wide2))
                    strcpy_s(toon[i], sizeof(toon[i]), text);
            }
        }
    } else {
        for (int i = 0; i < 10; ++i) {
            sprintf_s(text, 0x100, "toon%02d.bmp", i + 1);
            strcpy_s(model.pmdToonFileNames[i],
                     sizeof(model.pmdToonFileNames[i]), text);
        }
    }

    // ---- rigid bodies + joints (physics) ----------------------------------
    // gated on the rigid-count read itself (original: _read(...) != -1)
    const int rbRead = _read(fh, &model.rigidCount, sizeof(model.rigidCount));
    const std::uint32_t rigidCount = model.rigidCount;
    if (rbRead != -1) {
        PhysicsScene* physScene = mdl::Mdl(m)->scenePtr;
        SetPhysicsMode(m, 0, nullptr, 0);                    // 0x4A9220
        SetPhysicsMode(m, 1, nullptr, 0);
        mdl::RigidRecord* rigids = static_cast<mdl::RigidRecord*>(
            operator new(sizeof(mdl::RigidRecord) *
                         (rigidCount ? rigidCount : 1)));
        mdl::Rigids(m) = rigids;
        std::memset(rigids, 0, sizeof(mdl::RigidRecord) *
                                  (rigidCount ? rigidCount : 1));
        for (std::uint32_t i = 0; i < rigidCount; ++i) {
            mdl::RigidRecord& rigid = rigids[i];
            _read(fh, rigid.name, sizeof(rigid.name));
            std::int16_t boneIndex = -1;
            _read(fh, &boneIndex, sizeof(boneIndex));
            rigid.boneIndex = boneIndex;
            _read(fh, &rigid.group, sizeof(rigid.group));
            _read(fh, &rigid.noCollapse, sizeof(rigid.noCollapse));
            _read(fh, &rigid.shape, sizeof(rigid.shape));
            _read(fh, rigid.size, sizeof(rigid.size));
            _read(fh, rigid.position, sizeof(rigid.position));
            _read(fh, rigid.rotation, sizeof(rigid.rotation));
            _read(fh, &rigid.mass, sizeof(rigid.mass));
            _read(fh, &rigid.linearDamping, sizeof(rigid.linearDamping));
            _read(fh, &rigid.angularDamping, sizeof(rigid.angularDamping));
            _read(fh, &rigid.restitution, sizeof(rigid.restitution));
            _read(fh, &rigid.friction, sizeof(rigid.friction));
            _read(fh, &rigid.mode, sizeof(rigid.mode));
            rigid.kinematicFlag = rigid.mode == 2 ? 1 : 0;
            rigid.staticFlag = rigid.mode == 0 ? 1 : 0;

            if (haveD3dx) {
                using d3dx::D3DXMATRIXF;
                D3DXMATRIXF mat, tmp;
                d3dx->rotZ(&mat, rigid.rotation[2]);
                d3dx->rotX(&tmp, rigid.rotation[0]);
                d3dx->multiply(&mat, &mat, &tmp);
                d3dx->rotY(&tmp, rigid.rotation[1]);
                d3dx->multiply(&mat, &mat, &tmp);
                d3dx->translation(&tmp, rigid.position[0], rigid.position[1],
                                  rigid.position[2]);
                d3dx->multiply(&mat, &mat, &tmp);
                const std::int32_t boneIdx = rigid.boneIndex;
                LogPmdRigid(path, i, boneIdx, boneCount, bones);
                const float* bp;
                if (boneIdx < 0)
                    bp = reinterpret_cast<const float*>(bones->position);
                else
                    bp = reinterpret_cast<const float*>(&bones[boneIdx].position[0]);
                d3dx->translation(&tmp, bp[0], bp[1], bp[2]);
                d3dx->multiply(&mat, &mat, &tmp);
                // create the Bullet body (shape + limits + world add)
                void* bodyOut[2] = {nullptr, nullptr};
                CreateRigidBody(physScene, bodyOut, rigid.shape, rigid.size[0],
                                rigid.size[1], rigid.size[2],
                                reinterpret_cast<const float*>(&mat),
                                rigid.mode, rigid.mass, rigid.linearDamping,
                                rigid.angularDamping, rigid.restitution,
                                rigid.friction, static_cast<char>(rigid.group),
                                rigid.noCollapse); // 0x4064F0
                rigid.keyData = bodyOut[0];
                rigid.body = bodyOut[1];
                const std::int32_t bi = rigid.boneIndex;
                if (rigid.mode > 0 && bi >= 0)
                    bones[bi].hasRigidBody = 1;
                D3DXMATRIXF inv, t2;
                // The original indexes the x86 bone record as float[77..79]
                // (its `position` member).  That indexing crosses the two
                // widened text pointers on x64, so it reads the tail of
                // matExtra instead of the rest position.  The inverse rigid
                // transform is also the basis for every joint anchor and for
                // physics readback; use the ABI-independent member here.
                const mdl::BoneRecord& linkedBone =
                    bones[boneIdx < 0 ? 0 : boneIdx];
                const float* bonePosition = linkedBone.position;
                d3dx->translation(&inv, -bonePosition[0], -bonePosition[1],
                                  -bonePosition[2]);
                d3dx->translation(&t2, -rigid.position[0], -rigid.position[1],
                                  -rigid.position[2]);
                d3dx->multiply(&inv, &inv, &t2);
                d3dx->rotY(&t2, -rigid.rotation[1]);
                d3dx->multiply(&inv, &inv, &t2);
                d3dx->rotX(&t2, -rigid.rotation[0]);
                d3dx->multiply(&inv, &inv, &t2);
                d3dx->rotZ(&t2, -rigid.rotation[2]);
                d3dx->multiply(&inv, &inv, &t2);
                std::memcpy(rigid.invTransform, &inv, sizeof(inv));
            }
        }
        _read(fh, &model.jointCount, sizeof(model.jointCount));
        const std::uint32_t jointCount = model.jointCount;
        mdl::JointRecord* joints = static_cast<mdl::JointRecord*>(
            operator new(sizeof(mdl::JointRecord) *
                         (jointCount ? jointCount : 1)));
        mdl::Joints(m) = joints;
        std::memset(joints, 0, sizeof(mdl::JointRecord) *
                                  (jointCount ? jointCount : 1));
        for (std::uint32_t i = 0; i < jointCount; ++i) {
            mdl::JointRecord& joint = joints[i];
            _read(fh, joint.name, sizeof(joint.name));
            // 26 four-byte fields in the original's shuffled order
            // (0x4C14FB..0x4C1749).  The leading 0 entry in an earlier
            // port silently replaced this name read, shorting each record
            // by 16 bytes and desynchronising the stream - wild rigid
            // indices, AV in memcpy; found by desktop testing with
            // Luka_Megurine.pmd, docs/ARCHITECTURE.md §8.
            _read(fh, &joint.rigidA, sizeof(joint.rigidA));
            _read(fh, &joint.rigidB, sizeof(joint.rigidB));
            _read(fh, joint.position, sizeof(joint.position));
            _read(fh, joint.rotation, sizeof(joint.rotation));
            _read(fh, &joint.limits[3], 3 * sizeof(float));
            _read(fh, &joint.limits[0], 3 * sizeof(float));
            _read(fh, &joint.limits[9], 3 * sizeof(float));
            _read(fh, &joint.limits[6], 3 * sizeof(float));
            _read(fh, joint.springs, sizeof(joint.springs));
            if (haveD3dx) {
                using d3dx::D3DXMATRIXF;
                mdl::RigidRecord* rigids2 = mdl::Rigids(m);
                const std::int32_t a = joint.rigidA;
                const std::int32_t b = joint.rigidB;
                mdl::RigidRecord& rigidA = rigids2[a];
                mdl::RigidRecord& rigidB = rigids2[b];
                D3DXMATRIXF ma, mb, rot;
                std::memcpy(&ma, rigidA.invTransform, sizeof(ma));
                std::memcpy(&mb, rigidB.invTransform, sizeof(mb));
                // pivot A
                const float* point = joint.position;
                float pivotA[3], pivotB[3];
                TransformJointPointOriginal(pivotA, point, &ma.m[0][0]);
                TransformJointPointOriginal(pivotB, point, &mb.m[0][0]);
                const float ax = pivotA[0], ay = pivotA[1], az = pivotA[2];
                const float bx = pivotB[0], by = pivotB[1], bz = pivotB[2];
                const float distA =
                    std::sqrt(ax * ax + ay * ay + az * az);
                const float distB =
                    std::sqrt(bx * bx + by * by + bz * bz);
                // 过拉伸限位半径：限位范数叠加两锚点距离
                // （x64 @0x7FF7CB4D51B0..0x4D526D，见 JointRadiusBound）
                joint.radiusBound = JointRadiusBound(joint.limits, distA, distB);
                d3dx->rotZ(&rot, joint.rotation[2]);
                D3DXMATRIXF t2;
                d3dx->rotX(&t2, joint.rotation[0]);
                d3dx->multiply(&rot, &rot, &t2);
                d3dx->rotY(&t2, joint.rotation[1]);
                d3dx->multiply(&rot, &rot, &t2);
                d3dx->rotY(&t2, -rigidA.rotation[1]);
                d3dx->multiply(&rot, &rot, &t2);
                d3dx->rotX(&t2, -rigidA.rotation[0]);
                d3dx->multiply(&rot, &rot, &t2);
                d3dx->rotZ(&t2, -rigidA.rotation[2]);
                d3dx->multiply(&rot, &rot, &t2);
                float qa[4];
                d3dx->quatFromMatrix(qa, &rot);
                d3dx->rotZ(&rot, joint.rotation[2]);
                d3dx->rotX(&t2, joint.rotation[0]);
                d3dx->multiply(&rot, &rot, &t2);
                d3dx->rotY(&t2, joint.rotation[1]);
                d3dx->multiply(&rot, &rot, &t2);
                d3dx->rotY(&t2, -rigidB.rotation[1]);
                d3dx->multiply(&rot, &rot, &t2);
                d3dx->rotX(&t2, -rigidB.rotation[0]);
                d3dx->multiply(&rot, &rot, &t2);
                d3dx->rotZ(&t2, -rigidB.rotation[2]);
                d3dx->multiply(&rot, &rot, &t2);
                float qb[4];
                d3dx->quatFromMatrix(qb, &rot);
                joint.constraint = CreatePhysJoint(
                    physScene,
                    rigidA.body, rigidB.body,
                    ax, ay, az, qa[0], qa[1], qa[2], qa[3],
                    bx, by, bz, qb[0], qb[1], qb[2], qb[3],
                    joint.limits[0], joint.limits[1], joint.limits[2],
                    joint.limits[3], joint.limits[4], joint.limits[5],
                    joint.limits[6], joint.limits[7], joint.limits[8],
                    joint.limits[9], joint.limits[10], joint.limits[11],
                    joint.springs[0], joint.springs[1], joint.springs[2],
                    joint.springs[3], joint.springs[4],
                    joint.springs[5]);  // 0x406010
            }
        }
    }

    _close(fh);

    // ---- animation pools --------------------------------------------------
    {
        mdl::BoneKeys(m) = static_cast<mdl::BoneKey*>(
            operator new(sizeof(mdl::BoneKey) * mdl::kBoneKeyCapacity));
        std::memset(mdl::BoneKeys(m), 0,
                    sizeof(mdl::BoneKey) * mdl::kBoneKeyCapacity);
        mdl::MorphKeys(m) = static_cast<mdl::MorphKey*>(
            operator new(sizeof(mdl::MorphKey) * mdl::kMorphKeyCapacity));
        std::memset(mdl::MorphKeys(m), 0,
                    sizeof(mdl::MorphKey) * mdl::kMorphKeyCapacity);
        mdl::DisplayKeys(m) = static_cast<mdl::DisplayKey*>(
            operator new(sizeof(mdl::DisplayKey) * mdl::kDisplayKeyCapacity));
        std::memset(mdl::DisplayKeys(m), 0,
                    sizeof(mdl::DisplayKey) * mdl::kDisplayKeyCapacity);
        const std::uint32_t ikn = model.ikChainCount;
        const std::uint32_t ctr = model.boneOrderCount;
        for (std::size_t keyIndex = 0;
             keyIndex < mdl::kDisplayKeyCapacity; ++keyIndex) {
            mdl::DisplayKey& key = mdl::DisplayKeys(m)[keyIndex];
            if (ikn > 0) {
                auto* flags = static_cast<std::uint8_t*>(operator new(ikn));
                mdl::IkStates(key) = flags;
                for (std::uint32_t k = 0; k < ikn; ++k)
                    flags[k] = 1;
            }
            key.visible = 1;
            if (static_cast<std::int32_t>(ctr) > 0) {
                auto* pairs = static_cast<mdl::BoneReference*>(
                    operator new(sizeof(mdl::BoneReference) * ctr));
                mdl::SelectorStates(key) = pairs;
                for (std::uint32_t k = 0; k < ctr; ++k) {
                    pairs[k].modelIndex = -1;
                    pairs[k].boneIndex = 0;
                }
            }
        }
        mdl::BoneKeyIndices(m) = static_cast<std::uint32_t*>(
            operator new(sizeof(*mdl::BoneKeyIndices(m)) * boneCount));
        mdl::MorphKeyIndices(m) = static_cast<std::uint32_t*>(
            operator new(sizeof(*mdl::MorphKeyIndices(m)) * model.morphCount));
        for (std::uint32_t i = 0; i < boneCount; ++i) {
            mdl::BoneKey& row = mdl::BoneKeys(m)[i];
            for (int k = 0; k < 4; ++k) {
                row.interpolation[k] = 20;
                row.interpolation[k + 4] = 20;
                row.interpolation[k + 8] = 107;
                row.interpolation[k + 12] = 107;
            }
            row.rotation[3] = 1.0f;
        }
    }
    model.loadComplete = 1;
    PostLoadInit(m);                                          // 0x49C850
    return true;
}

}  // namespace mikudancestudio
