# VERSION is the sole editable product version; preserve its two-digit minor.
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/VERSION")
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/VERSION" MDS_VERSION)
string(STRIP "${MDS_VERSION}" MDS_VERSION)
if(NOT MDS_VERSION MATCHES "^([1-9][0-9]*)[.]([0-9][0-9])$")
    message(FATAL_ERROR "VERSION must have the form 10.00 (major.two-digit-minor)")
endif()
set(MDS_VERSION_MAJOR "${CMAKE_MATCH_1}")
set(MDS_VERSION_MINOR "${CMAKE_MATCH_2}")
string(REGEX REPLACE "^0+" "" MDS_VERSION_MINOR "${MDS_VERSION_MINOR}")
if(MDS_VERSION_MINOR STREQUAL "")
    set(MDS_VERSION_MINOR 0)
endif()
if(MDS_VERSION_MAJOR GREATER 65535)
    message(FATAL_ERROR "VERSION major exceeds the Windows version-resource limit")
endif()
